const testimonialsData = [
    // Featured Client Testimonials (6)
    {
        key: 0,
        featured: true,
        image: "/images/CLIENTS/elegant_business_woman.jpg",
        name: "Linda L.",
        position: "Client",
        description: "I cannot say enough good things about Jonah. He's attentive, compassionate, professional and highly dedicated to helping good people deal with bad situations. If you're looking for representation, I highly recommend the Law Offices of Jonah Chew.",
        class: "AboveContainer",
        star: 5,
    },
    {
        key: 1,
        featured: true,
        image: "/images/CLIENTS/congressman.jpg",
        name: "John G.",
        position: "Client",
        description: "I had multiple DUIs and a felony case - was going to prison. Jonah got dismissals and a minor probation violation. He's the most aggressive, respected lawyer I've ever encountered. RUN to his office if you have a court date.",
        class: "AboveContainer",
        star: 5,
    },
    {
        key: 2,
        featured: true,
        image: "/images/CLIENTS/young_business_woman.jpg",
        name: "Marina G.",
        position: "Client",
        description: "My daughter was charged with a felony. Jonah worked tirelessly for 7 months and got the case dismissed. He made the stressful situation bearable and we found a lawyer we can truly trust.",
        class: "AboveContainer",
        star: 5,
    },
    {
        key: 3,
        featured: true,
        image: "/images/CLIENTS/experienced_attorney.jpg",
        name: "Vince C.",
        position: "Client",
        description: "Jonah displayed unparalleled professionalism. Despite his heavy caseload, he ensured all my needs were addressed. His communication, and depth of knowledge was simply amazing.",
        class: "BelowContainer",
        star: 5,
    },
    {
        key: 4,
        featured: true,
        image: "/images/CLIENTS/congressman.jpg",
        name: "Tony T.",
        position: "Client",
        description: "Exceeded my expectations with his compassion, knowledge of the court system, and intellect. I came from Los Angeles to see him and it was the best decision I could have made.",
        class: "BelowContainer",
        star: 5,
    },
    {
        key: 5,
        featured: true,
        image: "/images/CLIENTS/elegant_business_woman.jpg",
        name: "Shannah G.",
        position: "Client",
        description: "Jonah took care of my cousin who was falsely accused. He fought hard in court while keeping her informed and protected. His hard work led to a complete dismissal of the case.",
        class: "BelowContainer",
        star: 5,
    },

    // Additional Client Testimonials
    {
        key: 6,
        featured: false,
        image: "/images/CLIENTS/Boy04.webp",
        name: "Ryan N.",
        position: "Client",
        description: "Great lawyer. Never kept me in the dark about my case. Very responsive by email and phone. I was wrongfully accused and Jonah got my case dismissed.",
        class: "AboveContainer",
        star: 5,
    },
    {
        key: 7,
        featured: false,
        image: "/images/CLIENTS/Boy04.webp",
        name: "Shawn A.",
        position: "Client",
        description: "Jonah is well known and respected in the court system. From our first meeting he made me feel at ease and got me the best possible outcome for my case.",
        class: "AboveContainer",
        star: 5,
    },
    {
        key: 8,
        featured: false,
        image: "/images/CLIENTS/Boy04.webp",
        name: "Eduino M.",
        position: "Client",
        description: "Very courteous and professional. Always kept me informed and answered emails promptly. I will definitely hire him again and recommend him to others.",
        class: "BelowContainer",
        star: 5,
    },
    {
        key: 9,
        featured: false,
        image: "/images/CLIENTS/Boy04.webp",
        name: "Ryan N.",
        position: "Client",
        description: "Always kept me up to date and responded in less than one day. Communication is very important to me and Jonah exceeded my expectations.",
        class: "BelowContainer",
        star: 5,
    },

    // Featured Attorney Testimonials (6)
    {
        key: 10,
        featured: true,
        image: "/images/CLIENTS/Girl03.webp",
        name: "Givelle L.",
        position: "Criminal Defense Attorney",
        description: "Jonah is one of the best, if not THE BEST attorneys out there. He knows the law like the back of his hand and has a great reputation. We've worked together on many cases and our clients could not be happier.",
        class: "AboveContainer",
        star: 5,
    },
    {
        key: 11,
        featured: true,
        image: "/images/CLIENTS/Boy04.webp",
        name: "Christopher L.",
        position: "Mediation Attorney",
        description: "I continue to learn from him after 24 years as a judge, magistrate, and prosecutor. You cannot afford not to hire him. I endorse without any reservations.",
        class: "AboveContainer",
        star: 5,
    },
    {
        key: 12,
        featured: true,
        image: "/images/CLIENTS/Boy04.webp",
        name: "D.L. R.",
        position: "Personal Injury Attorney",
        description: "Jonah represents a standard all attorneys should pursue. Detail-oriented, knowledgeable, and relentless in his pursuit of justice. I unequivocally endorse Jonah Chew.",
        class: "AboveContainer",
        star: 5,
    },
    {
        key: 13,
        featured: true,
        image: "/images/CLIENTS/Boy04.webp",
        name: "Chris F.",
        position: "Criminal Defense Attorney",
        description: "As a former DA who opposed Jonah, I can say he spots small issues in big cases and uses them to benefit his clients. He is knowledgeable, experienced, and I endorse him fully.",
        class: "BelowContainer",
        star: 5,
    },
    {
        key: 14,
        featured: true,
        image: "/images/CLIENTS/Boy04.webp",
        name: "Peter F.",
        position: "Criminal Defense Attorney",
        description: "One of the finest, most prepared criminal defense lawyers in the Bay Area. Very well respected by Judges, Prosecutors, and fellow lawyers. Highly recommended.",
        class: "BelowContainer",
        star: 5,
    },
    {
        key: 15,
        featured: true,
        image: "/images/CLIENTS/Boy04.webp",
        name: "Francisco R.",
        position: "DUI Attorney",
        description: "He truly cares about his clients and will go to hell and back to represent you better than anyone else! A hell of a litigator who knows his cases better than anyone in the courtroom.",
        class: "BelowContainer",
        star: 5,
    },

    // Additional Attorney Testimonials
    {
        key: 16,
        featured: false,
        image: "/images/CLIENTS/Boy04.webp",
        name: "Curtis B.",
        position: "Criminal Defense Attorney",
        description: "Extremely knowledgeable, confident, and helpful. Well known in Bay Area courts and always fights for his clients. Great lawyer!",
        class: "AboveContainer",
        star: 5,
    },
    {
        key: 17,
        featured: false,
        image: "/images/CLIENTS/Boy04.webp",
        name: "John S.",
        position: "DUI Attorney",
        description: "Highly respected aggressive criminal defense advocate. Works tirelessly to achieve the best possible results and isn't afraid to stand up to the government.",
        class: "AboveContainer",
        star: 5,
    },
    {
        key: 18,
        featured: false,
        image: "/images/CLIENTS/Boy04.webp",
        name: "Daniel F.",
        position: "Criminal Defense Attorney",
        description: "An excellent criminal defense lawyer. Knows the law, how to argue it, how to pitch a deal, and how to win. We've worked together for two years.",
        class: "BelowContainer",
        star: 5,
    },
    {
        key: 19,
        featured: false,
        image: "/images/CLIENTS/Boy04.webp",
        name: "Peter C.",
        position: "DUI Attorney",
        description: "Very experienced and knowledgeable. The ultimate fighter for his clients. One of the best, if not the best, in the San Francisco Bay Area.",
        class: "BelowContainer",
        star: 5,
    }
];

export default testimonialsData;